# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci --no-fund
      - name: Test Format
        run: npm run test:format
      - name: Unit Test
        run: npm run test:unit
      - name: Build
        run: npm run build
      - name: Test Size
        run: npm run test:size
      - name: Type-check UI
        run: npm run test:types:ui
      - name: Test UI
        run: npm run test:ui
